// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9EeOW4DzQADiKwkdjr6YIrpNtKQhc0HA',
    appId: '1:571874082341:web:6f21042dfbe6fc2f3749cc',
    messagingSenderId: '571874082341',
    projectId: 'sign-up-in-ea5fd',
    authDomain: 'sign-up-in-ea5fd.firebaseapp.com',
    storageBucket: 'sign-up-in-ea5fd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwIIKq19OjEXQGKiuLD6cX_XhLH3OGJQk',
    appId: '1:571874082341:android:e1f680f7b9e139f63749cc',
    messagingSenderId: '571874082341',
    projectId: 'sign-up-in-ea5fd',
    storageBucket: 'sign-up-in-ea5fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfDlj_s8xPsIV8XO5-3pMuEEyxphUbz80',
    appId: '1:571874082341:ios:a66b80566b1ed61e3749cc',
    messagingSenderId: '571874082341',
    projectId: 'sign-up-in-ea5fd',
    storageBucket: 'sign-up-in-ea5fd.firebasestorage.app',
    iosClientId: '571874082341-nka71bn1ccfsecns6nrt56uesji47b9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.signUpIn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfDlj_s8xPsIV8XO5-3pMuEEyxphUbz80',
    appId: '1:571874082341:ios:a66b80566b1ed61e3749cc',
    messagingSenderId: '571874082341',
    projectId: 'sign-up-in-ea5fd',
    storageBucket: 'sign-up-in-ea5fd.firebasestorage.app',
    iosClientId: '571874082341-nka71bn1ccfsecns6nrt56uesji47b9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.signUpIn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9EeOW4DzQADiKwkdjr6YIrpNtKQhc0HA',
    appId: '1:571874082341:web:fd12b1c21f3a75c13749cc',
    messagingSenderId: '571874082341',
    projectId: 'sign-up-in-ea5fd',
    authDomain: 'sign-up-in-ea5fd.firebaseapp.com',
    storageBucket: 'sign-up-in-ea5fd.firebasestorage.app',
  );

}